### ISSUE TITLE
[V3] Tags for createDraftListing / updateListing: string[] vs string

### ISSUE THREAD

**Issue by kapik** [Granga/etsy-ts#13]
Hello 👋

There is a confusion in the api documentation for the `createDraftListing` and `updateListing` methods.
The `tags` property must be a `string` (each tag separated by a comma) and not an `Array of strings`.

🚀

**Comment by Granga** [comment]
So the problem is the following: 
The API documentation tells us that `tags` should be sent as an array of strings.
In reality, the API expects the `tags` property to be one string in which tags are separated by comma. 
I consider this to be a problem in Etsy API documentation and this inconsistency should be reported there. This API client is automatically generated from the documentation.

Until they fix it my suggested workaround is to silence typescript by casting the tags string to `any`.


```typescript
await client.ShopListing.updateListing(shopId, listingId, {
	tags: ["First", "Second", "Third"].join(",") as any
}, tokens);
```
